[package]
name = "system_info"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.33.1"
serde = { version = "1.0.213", features = ["derive"] }
dirs = "5.0"
tokio = { version = "1.41.1", features = ["full"] }
winapi = { version = "0.3", features = ["fileapi"] }